name: Spec

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        ruby:
          - '3.3.0'
          - '3.2.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the specs
      run: bundle exec rspec
    - name: SimpleCov Coverage
      uses: joshmfrankel/simplecov-check-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_suite_coverage: 85
